### ISSUE TITLE
no output produced for seemingly well-formed compile_commands.json

### ISSUE THREAD

**Issue by shrouxm** [sourcegraph/lsif-clang#4] opened 2020-08-18 00:30 UTC
technical details are private, but the gist is that the tool builds successfully, and a compile_commands is generated by the user's distributed build system. when the tool is run, no frontend compilation occurs and the output dump.lsif contains only a meta and project vertex. nothing looks suspicious in the compile_commands.json, but some details to note:
- the same file is compiled multiple times with different options
- the file may not have been generated on the same machine the tool is being run on

**Comment by aidaeology** [comment] 2020-09-24 19:05
@gbrik What is the status of this issue, was this resolved with the 3.20 milestone or does it still need work? If it's resolved and longer a problem then please mark as closed and link the relevant PR. Otherwise please provide a status update here on what the remaining work is to get it resolved.

**Comment by gbrik** [comment] 2020-09-28 21:10
I need to reach out to the user to set up a call so we can work together on this, as I haven't been able to reproduce the issue async.

**Comment by suo** [comment] 2020-10-16 21:36
I have a similar issue, maybe mine is a bit easier to repro since the code is public (PyTorch). This is my `dump.lsif`: [dump.lsif.zip](https://github.com/sourcegraph/lsif-clang/files/5394409/dump.lsif.zip)

To repro (linux):
1. Follow the instructions to install dependencies and get the source: https://github.com/pytorch/pytorch#install-dependencies
2. Use the following build command to build a minimal thing:
```
BUILD_TESTS=0 BUILD_CAFFE2_OPS=0 USE_OPENMP=0 USE_MKL=0 USE_MKLDNN=0 USE_NNPACK=0 USE_XNNPACK=0 USE_QNNPACK=0 USE_PYTORCH_QNNPACK=0 USE_FBGEMM=0 USE_DISTRIBUTED=0 USE_CUDA=0 python setup.py -q develop
3. The previous command will automatically create `compile_commands.json`. 

The output of `lsif-clang` seems reasonable, it looks like it's properly processing files. But the `lsif.dump` is effectively empty.

**Comment by gbrik** [comment] 2020-10-19 21:17
Hi @suo, thanks for reporting! Yours might be a slightly different issue than the one reported above, since in the original case it looked like lsif-clang wasn't doing any processing at all.

Having said that, I was able to produce an index for pytorch using the build command you posted and then running `lsif-clang compile_commands.json` in the project's root. Could you post exactly how you're invoking `lsif-clang`? The most likely culprit I can think of is if the `project-root` argument isn't set correctly (`lsif-clang` drops all data outside of this root, if it's unset it uses the working directory).

I also just pushed a quick commit so that if you run `lsif-clang --debug compile_commands.json` it should show you what `lsif-clang` is trying to use as the project root.

**Comment by gbrik** [comment] 2021-02-14 21:07
It turned out this issue was due to a compile_flags.txt in a parent directory, will be closed by updating documentation.

**Closed** 2021-03-29 16:24 UTC
Labels: bug, team/code-intelligence
